import type { Metadata } from "next";
import "./globals.css";
// import AuthContext from "./components/context/AuthContext";
import Footer from "./components/Footer";
import React from "react";
import AuthProvider from "./components/context/AuthContext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main style={{ flex: 1 }}></main>
        <AuthProvider children={children} />

        <Footer />
      </body>
    </html>
  );
}